/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSubmitCommunityRouteImport } from './routes/_app.submit.community'
import { Route as AppRCommunityNameRouteImport } from './routes/_app.r.$communityName'
import { Route as AppModCommunityNameRouteImport } from './routes/_app.mod.$communityName'
import { Route as AppRCommunityNameIndexRouteImport } from './routes/_app.r.$communityName.index'
import { Route as AppModCommunityNameIndexRouteImport } from './routes/_app.mod.$communityName.index'
import { Route as AppRCommunityNameSubmitRouteImport } from './routes/_app.r.$communityName.submit'
import { Route as AppModCommunityNameModeratorsRouteImport } from './routes/_app.mod.$communityName.moderators'
import { Route as AppModCommunityNameInvitesRouteImport } from './routes/_app.mod.$communityName.invites'
import { Route as AppModCommunityNameApprovedUsersRouteImport } from './routes/_app.mod.$communityName.approved-users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmitCommunityRoute = AppSubmitCommunityRouteImport.update({
  id: '/submit/community',
  path: '/submit/community',
  getParentRoute: () => AppRoute,
} as any)
const AppRCommunityNameRoute = AppRCommunityNameRouteImport.update({
  id: '/r/$communityName',
  path: '/r/$communityName',
  getParentRoute: () => AppRoute,
} as any)
const AppModCommunityNameRoute = AppModCommunityNameRouteImport.update({
  id: '/mod/$communityName',
  path: '/mod/$communityName',
  getParentRoute: () => AppRoute,
} as any)
const AppRCommunityNameIndexRoute = AppRCommunityNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRCommunityNameRoute,
} as any)
const AppModCommunityNameIndexRoute =
  AppModCommunityNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppModCommunityNameRoute,
  } as any)
const AppRCommunityNameSubmitRoute = AppRCommunityNameSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AppRCommunityNameRoute,
} as any)
const AppModCommunityNameModeratorsRoute =
  AppModCommunityNameModeratorsRouteImport.update({
    id: '/moderators',
    path: '/moderators',
    getParentRoute: () => AppModCommunityNameRoute,
  } as any)
const AppModCommunityNameInvitesRoute =
  AppModCommunityNameInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AppModCommunityNameRoute,
  } as any)
const AppModCommunityNameApprovedUsersRoute =
  AppModCommunityNameApprovedUsersRouteImport.update({
    id: '/approved-users',
    path: '/approved-users',
    getParentRoute: () => AppModCommunityNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/mod/$communityName': typeof AppModCommunityNameRouteWithChildren
  '/r/$communityName': typeof AppRCommunityNameRouteWithChildren
  '/submit/community': typeof AppSubmitCommunityRoute
  '/mod/$communityName/approved-users': typeof AppModCommunityNameApprovedUsersRoute
  '/mod/$communityName/invites': typeof AppModCommunityNameInvitesRoute
  '/mod/$communityName/moderators': typeof AppModCommunityNameModeratorsRoute
  '/r/$communityName/submit': typeof AppRCommunityNameSubmitRoute
  '/mod/$communityName/': typeof AppModCommunityNameIndexRoute
  '/r/$communityName/': typeof AppRCommunityNameIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/submit/community': typeof AppSubmitCommunityRoute
  '/mod/$communityName/approved-users': typeof AppModCommunityNameApprovedUsersRoute
  '/mod/$communityName/invites': typeof AppModCommunityNameInvitesRoute
  '/mod/$communityName/moderators': typeof AppModCommunityNameModeratorsRoute
  '/r/$communityName/submit': typeof AppRCommunityNameSubmitRoute
  '/mod/$communityName': typeof AppModCommunityNameIndexRoute
  '/r/$communityName': typeof AppRCommunityNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/mod/$communityName': typeof AppModCommunityNameRouteWithChildren
  '/_app/r/$communityName': typeof AppRCommunityNameRouteWithChildren
  '/_app/submit/community': typeof AppSubmitCommunityRoute
  '/_app/mod/$communityName/approved-users': typeof AppModCommunityNameApprovedUsersRoute
  '/_app/mod/$communityName/invites': typeof AppModCommunityNameInvitesRoute
  '/_app/mod/$communityName/moderators': typeof AppModCommunityNameModeratorsRoute
  '/_app/r/$communityName/submit': typeof AppRCommunityNameSubmitRoute
  '/_app/mod/$communityName/': typeof AppModCommunityNameIndexRoute
  '/_app/r/$communityName/': typeof AppRCommunityNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/mod/$communityName'
    | '/r/$communityName'
    | '/submit/community'
    | '/mod/$communityName/approved-users'
    | '/mod/$communityName/invites'
    | '/mod/$communityName/moderators'
    | '/r/$communityName/submit'
    | '/mod/$communityName/'
    | '/r/$communityName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/submit/community'
    | '/mod/$communityName/approved-users'
    | '/mod/$communityName/invites'
    | '/mod/$communityName/moderators'
    | '/r/$communityName/submit'
    | '/mod/$communityName'
    | '/r/$communityName'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/mod/$communityName'
    | '/_app/r/$communityName'
    | '/_app/submit/community'
    | '/_app/mod/$communityName/approved-users'
    | '/_app/mod/$communityName/invites'
    | '/_app/mod/$communityName/moderators'
    | '/_app/r/$communityName/submit'
    | '/_app/mod/$communityName/'
    | '/_app/r/$communityName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submit/community': {
      id: '/_app/submit/community'
      path: '/submit/community'
      fullPath: '/submit/community'
      preLoaderRoute: typeof AppSubmitCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/r/$communityName': {
      id: '/_app/r/$communityName'
      path: '/r/$communityName'
      fullPath: '/r/$communityName'
      preLoaderRoute: typeof AppRCommunityNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mod/$communityName': {
      id: '/_app/mod/$communityName'
      path: '/mod/$communityName'
      fullPath: '/mod/$communityName'
      preLoaderRoute: typeof AppModCommunityNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/r/$communityName/': {
      id: '/_app/r/$communityName/'
      path: '/'
      fullPath: '/r/$communityName/'
      preLoaderRoute: typeof AppRCommunityNameIndexRouteImport
      parentRoute: typeof AppRCommunityNameRoute
    }
    '/_app/mod/$communityName/': {
      id: '/_app/mod/$communityName/'
      path: '/'
      fullPath: '/mod/$communityName/'
      preLoaderRoute: typeof AppModCommunityNameIndexRouteImport
      parentRoute: typeof AppModCommunityNameRoute
    }
    '/_app/r/$communityName/submit': {
      id: '/_app/r/$communityName/submit'
      path: '/submit'
      fullPath: '/r/$communityName/submit'
      preLoaderRoute: typeof AppRCommunityNameSubmitRouteImport
      parentRoute: typeof AppRCommunityNameRoute
    }
    '/_app/mod/$communityName/moderators': {
      id: '/_app/mod/$communityName/moderators'
      path: '/moderators'
      fullPath: '/mod/$communityName/moderators'
      preLoaderRoute: typeof AppModCommunityNameModeratorsRouteImport
      parentRoute: typeof AppModCommunityNameRoute
    }
    '/_app/mod/$communityName/invites': {
      id: '/_app/mod/$communityName/invites'
      path: '/invites'
      fullPath: '/mod/$communityName/invites'
      preLoaderRoute: typeof AppModCommunityNameInvitesRouteImport
      parentRoute: typeof AppModCommunityNameRoute
    }
    '/_app/mod/$communityName/approved-users': {
      id: '/_app/mod/$communityName/approved-users'
      path: '/approved-users'
      fullPath: '/mod/$communityName/approved-users'
      preLoaderRoute: typeof AppModCommunityNameApprovedUsersRouteImport
      parentRoute: typeof AppModCommunityNameRoute
    }
  }
}

interface AppModCommunityNameRouteChildren {
  AppModCommunityNameApprovedUsersRoute: typeof AppModCommunityNameApprovedUsersRoute
  AppModCommunityNameInvitesRoute: typeof AppModCommunityNameInvitesRoute
  AppModCommunityNameModeratorsRoute: typeof AppModCommunityNameModeratorsRoute
  AppModCommunityNameIndexRoute: typeof AppModCommunityNameIndexRoute
}

const AppModCommunityNameRouteChildren: AppModCommunityNameRouteChildren = {
  AppModCommunityNameApprovedUsersRoute: AppModCommunityNameApprovedUsersRoute,
  AppModCommunityNameInvitesRoute: AppModCommunityNameInvitesRoute,
  AppModCommunityNameModeratorsRoute: AppModCommunityNameModeratorsRoute,
  AppModCommunityNameIndexRoute: AppModCommunityNameIndexRoute,
}

const AppModCommunityNameRouteWithChildren =
  AppModCommunityNameRoute._addFileChildren(AppModCommunityNameRouteChildren)

interface AppRCommunityNameRouteChildren {
  AppRCommunityNameSubmitRoute: typeof AppRCommunityNameSubmitRoute
  AppRCommunityNameIndexRoute: typeof AppRCommunityNameIndexRoute
}

const AppRCommunityNameRouteChildren: AppRCommunityNameRouteChildren = {
  AppRCommunityNameSubmitRoute: AppRCommunityNameSubmitRoute,
  AppRCommunityNameIndexRoute: AppRCommunityNameIndexRoute,
}

const AppRCommunityNameRouteWithChildren =
  AppRCommunityNameRoute._addFileChildren(AppRCommunityNameRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppModCommunityNameRoute: typeof AppModCommunityNameRouteWithChildren
  AppRCommunityNameRoute: typeof AppRCommunityNameRouteWithChildren
  AppSubmitCommunityRoute: typeof AppSubmitCommunityRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppModCommunityNameRoute: AppModCommunityNameRouteWithChildren,
  AppRCommunityNameRoute: AppRCommunityNameRouteWithChildren,
  AppSubmitCommunityRoute: AppSubmitCommunityRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
