/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as LoginSuccessIndexRouteImport } from './routes/login.success.index'
import { Route as AppUserUsernameRouteImport } from './routes/_app.user.$username'
import { Route as AppRCommunityNameRouteImport } from './routes/_app.r.$communityName'
import { Route as AppModCommunityNameRouteImport } from './routes/_app.mod.$communityName'
import { Route as AppRCommunityNameIndexRouteImport } from './routes/_app.r.$communityName.index'
import { Route as AppModCommunityNameIndexRouteImport } from './routes/_app.mod.$communityName.index'
import { Route as AppUserUsernameProfileRouteImport } from './routes/_app.user.$username._profile'
import { Route as AppRCommunityNameSubmitRouteImport } from './routes/_app.r.$communityName.submit'
import { Route as AppModCommunityNameModeratorsRouteImport } from './routes/_app.mod.$communityName.moderators'
import { Route as AppModCommunityNameInvitesRouteImport } from './routes/_app.mod.$communityName.invites'
import { Route as AppModCommunityNameApprovedUsersRouteImport } from './routes/_app.mod.$communityName.approved-users'
import { Route as AppUserUsernameProfileIndexRouteImport } from './routes/_app.user.$username._profile.index'
import { Route as AppUserUsernameProfileUpvotedIndexRouteImport } from './routes/_app.user.$username._profile.upvoted.index'
import { Route as AppUserUsernameProfileSubmittedIndexRouteImport } from './routes/_app.user.$username._profile.submitted.index'
import { Route as AppUserUsernameProfileSavedIndexRouteImport } from './routes/_app.user.$username._profile.saved.index'
import { Route as AppUserUsernameProfileDownvotedIndexRouteImport } from './routes/_app.user.$username._profile.downvoted.index'
import { Route as AppUserUsernameProfileCommentsIndexRouteImport } from './routes/_app.user.$username._profile.comments.index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LoginSuccessIndexRoute = LoginSuccessIndexRouteImport.update({
  id: '/login/success/',
  path: '/login/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserUsernameRoute = AppUserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppRCommunityNameRoute = AppRCommunityNameRouteImport.update({
  id: '/r/$communityName',
  path: '/r/$communityName',
  getParentRoute: () => AppRoute,
} as any)
const AppModCommunityNameRoute = AppModCommunityNameRouteImport.update({
  id: '/mod/$communityName',
  path: '/mod/$communityName',
  getParentRoute: () => AppRoute,
} as any)
const AppRCommunityNameIndexRoute = AppRCommunityNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRCommunityNameRoute,
} as any)
const AppModCommunityNameIndexRoute =
  AppModCommunityNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppModCommunityNameRoute,
  } as any)
const AppUserUsernameProfileRoute = AppUserUsernameProfileRouteImport.update({
  id: '/_profile',
  getParentRoute: () => AppUserUsernameRoute,
} as any)
const AppRCommunityNameSubmitRoute = AppRCommunityNameSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AppRCommunityNameRoute,
} as any)
const AppModCommunityNameModeratorsRoute =
  AppModCommunityNameModeratorsRouteImport.update({
    id: '/moderators',
    path: '/moderators',
    getParentRoute: () => AppModCommunityNameRoute,
  } as any)
const AppModCommunityNameInvitesRoute =
  AppModCommunityNameInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AppModCommunityNameRoute,
  } as any)
const AppModCommunityNameApprovedUsersRoute =
  AppModCommunityNameApprovedUsersRouteImport.update({
    id: '/approved-users',
    path: '/approved-users',
    getParentRoute: () => AppModCommunityNameRoute,
  } as any)
const AppUserUsernameProfileIndexRoute =
  AppUserUsernameProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppUserUsernameProfileRoute,
  } as any)
const AppUserUsernameProfileUpvotedIndexRoute =
  AppUserUsernameProfileUpvotedIndexRouteImport.update({
    id: '/upvoted/',
    path: '/upvoted/',
    getParentRoute: () => AppUserUsernameProfileRoute,
  } as any)
const AppUserUsernameProfileSubmittedIndexRoute =
  AppUserUsernameProfileSubmittedIndexRouteImport.update({
    id: '/submitted/',
    path: '/submitted/',
    getParentRoute: () => AppUserUsernameProfileRoute,
  } as any)
const AppUserUsernameProfileSavedIndexRoute =
  AppUserUsernameProfileSavedIndexRouteImport.update({
    id: '/saved/',
    path: '/saved/',
    getParentRoute: () => AppUserUsernameProfileRoute,
  } as any)
const AppUserUsernameProfileDownvotedIndexRoute =
  AppUserUsernameProfileDownvotedIndexRouteImport.update({
    id: '/downvoted/',
    path: '/downvoted/',
    getParentRoute: () => AppUserUsernameProfileRoute,
  } as any)
const AppUserUsernameProfileCommentsIndexRoute =
  AppUserUsernameProfileCommentsIndexRouteImport.update({
    id: '/comments/',
    path: '/comments/',
    getParentRoute: () => AppUserUsernameProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/signup': typeof SignupRoute
  '/': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/mod/$communityName': typeof AppModCommunityNameRouteWithChildren
  '/r/$communityName': typeof AppRCommunityNameRouteWithChildren
  '/user/$username': typeof AppUserUsernameProfileRouteWithChildren
  '/login/success': typeof LoginSuccessIndexRoute
  '/mod/$communityName/approved-users': typeof AppModCommunityNameApprovedUsersRoute
  '/mod/$communityName/invites': typeof AppModCommunityNameInvitesRoute
  '/mod/$communityName/moderators': typeof AppModCommunityNameModeratorsRoute
  '/r/$communityName/submit': typeof AppRCommunityNameSubmitRoute
  '/mod/$communityName/': typeof AppModCommunityNameIndexRoute
  '/r/$communityName/': typeof AppRCommunityNameIndexRoute
  '/user/$username/': typeof AppUserUsernameProfileIndexRoute
  '/user/$username/comments': typeof AppUserUsernameProfileCommentsIndexRoute
  '/user/$username/downvoted': typeof AppUserUsernameProfileDownvotedIndexRoute
  '/user/$username/saved': typeof AppUserUsernameProfileSavedIndexRoute
  '/user/$username/submitted': typeof AppUserUsernameProfileSubmittedIndexRoute
  '/user/$username/upvoted': typeof AppUserUsernameProfileUpvotedIndexRoute
}
export interface FileRoutesByTo {
  '/signup': typeof SignupRoute
  '/': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/user/$username': typeof AppUserUsernameProfileIndexRoute
  '/login/success': typeof LoginSuccessIndexRoute
  '/mod/$communityName/approved-users': typeof AppModCommunityNameApprovedUsersRoute
  '/mod/$communityName/invites': typeof AppModCommunityNameInvitesRoute
  '/mod/$communityName/moderators': typeof AppModCommunityNameModeratorsRoute
  '/r/$communityName/submit': typeof AppRCommunityNameSubmitRoute
  '/mod/$communityName': typeof AppModCommunityNameIndexRoute
  '/r/$communityName': typeof AppRCommunityNameIndexRoute
  '/user/$username/comments': typeof AppUserUsernameProfileCommentsIndexRoute
  '/user/$username/downvoted': typeof AppUserUsernameProfileDownvotedIndexRoute
  '/user/$username/saved': typeof AppUserUsernameProfileSavedIndexRoute
  '/user/$username/submitted': typeof AppUserUsernameProfileSubmittedIndexRoute
  '/user/$username/upvoted': typeof AppUserUsernameProfileUpvotedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/signup': typeof SignupRoute
  '/_app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_app/mod/$communityName': typeof AppModCommunityNameRouteWithChildren
  '/_app/r/$communityName': typeof AppRCommunityNameRouteWithChildren
  '/_app/user/$username': typeof AppUserUsernameRouteWithChildren
  '/login/success/': typeof LoginSuccessIndexRoute
  '/_app/mod/$communityName/approved-users': typeof AppModCommunityNameApprovedUsersRoute
  '/_app/mod/$communityName/invites': typeof AppModCommunityNameInvitesRoute
  '/_app/mod/$communityName/moderators': typeof AppModCommunityNameModeratorsRoute
  '/_app/r/$communityName/submit': typeof AppRCommunityNameSubmitRoute
  '/_app/user/$username/_profile': typeof AppUserUsernameProfileRouteWithChildren
  '/_app/mod/$communityName/': typeof AppModCommunityNameIndexRoute
  '/_app/r/$communityName/': typeof AppRCommunityNameIndexRoute
  '/_app/user/$username/_profile/': typeof AppUserUsernameProfileIndexRoute
  '/_app/user/$username/_profile/comments/': typeof AppUserUsernameProfileCommentsIndexRoute
  '/_app/user/$username/_profile/downvoted/': typeof AppUserUsernameProfileDownvotedIndexRoute
  '/_app/user/$username/_profile/saved/': typeof AppUserUsernameProfileSavedIndexRoute
  '/_app/user/$username/_profile/submitted/': typeof AppUserUsernameProfileSubmittedIndexRoute
  '/_app/user/$username/_profile/upvoted/': typeof AppUserUsernameProfileUpvotedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signup'
    | '/'
    | '/login'
    | '/mod/$communityName'
    | '/r/$communityName'
    | '/user/$username'
    | '/login/success'
    | '/mod/$communityName/approved-users'
    | '/mod/$communityName/invites'
    | '/mod/$communityName/moderators'
    | '/r/$communityName/submit'
    | '/mod/$communityName/'
    | '/r/$communityName/'
    | '/user/$username/'
    | '/user/$username/comments'
    | '/user/$username/downvoted'
    | '/user/$username/saved'
    | '/user/$username/submitted'
    | '/user/$username/upvoted'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signup'
    | '/'
    | '/login'
    | '/user/$username'
    | '/login/success'
    | '/mod/$communityName/approved-users'
    | '/mod/$communityName/invites'
    | '/mod/$communityName/moderators'
    | '/r/$communityName/submit'
    | '/mod/$communityName'
    | '/r/$communityName'
    | '/user/$username/comments'
    | '/user/$username/downvoted'
    | '/user/$username/saved'
    | '/user/$username/submitted'
    | '/user/$username/upvoted'
  id:
    | '__root__'
    | '/_app'
    | '/signup'
    | '/_app/'
    | '/login/'
    | '/_app/mod/$communityName'
    | '/_app/r/$communityName'
    | '/_app/user/$username'
    | '/login/success/'
    | '/_app/mod/$communityName/approved-users'
    | '/_app/mod/$communityName/invites'
    | '/_app/mod/$communityName/moderators'
    | '/_app/r/$communityName/submit'
    | '/_app/user/$username/_profile'
    | '/_app/mod/$communityName/'
    | '/_app/r/$communityName/'
    | '/_app/user/$username/_profile/'
    | '/_app/user/$username/_profile/comments/'
    | '/_app/user/$username/_profile/downvoted/'
    | '/_app/user/$username/_profile/saved/'
    | '/_app/user/$username/_profile/submitted/'
    | '/_app/user/$username/_profile/upvoted/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignupRoute: typeof SignupRoute
  LoginIndexRoute: typeof LoginIndexRoute
  LoginSuccessIndexRoute: typeof LoginSuccessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/login/success/': {
      id: '/login/success/'
      path: '/login/success'
      fullPath: '/login/success'
      preLoaderRoute: typeof LoginSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/user/$username': {
      id: '/_app/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof AppUserUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/r/$communityName': {
      id: '/_app/r/$communityName'
      path: '/r/$communityName'
      fullPath: '/r/$communityName'
      preLoaderRoute: typeof AppRCommunityNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mod/$communityName': {
      id: '/_app/mod/$communityName'
      path: '/mod/$communityName'
      fullPath: '/mod/$communityName'
      preLoaderRoute: typeof AppModCommunityNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/r/$communityName/': {
      id: '/_app/r/$communityName/'
      path: '/'
      fullPath: '/r/$communityName/'
      preLoaderRoute: typeof AppRCommunityNameIndexRouteImport
      parentRoute: typeof AppRCommunityNameRoute
    }
    '/_app/mod/$communityName/': {
      id: '/_app/mod/$communityName/'
      path: '/'
      fullPath: '/mod/$communityName/'
      preLoaderRoute: typeof AppModCommunityNameIndexRouteImport
      parentRoute: typeof AppModCommunityNameRoute
    }
    '/_app/user/$username/_profile': {
      id: '/_app/user/$username/_profile'
      path: ''
      fullPath: '/user/$username'
      preLoaderRoute: typeof AppUserUsernameProfileRouteImport
      parentRoute: typeof AppUserUsernameRoute
    }
    '/_app/r/$communityName/submit': {
      id: '/_app/r/$communityName/submit'
      path: '/submit'
      fullPath: '/r/$communityName/submit'
      preLoaderRoute: typeof AppRCommunityNameSubmitRouteImport
      parentRoute: typeof AppRCommunityNameRoute
    }
    '/_app/mod/$communityName/moderators': {
      id: '/_app/mod/$communityName/moderators'
      path: '/moderators'
      fullPath: '/mod/$communityName/moderators'
      preLoaderRoute: typeof AppModCommunityNameModeratorsRouteImport
      parentRoute: typeof AppModCommunityNameRoute
    }
    '/_app/mod/$communityName/invites': {
      id: '/_app/mod/$communityName/invites'
      path: '/invites'
      fullPath: '/mod/$communityName/invites'
      preLoaderRoute: typeof AppModCommunityNameInvitesRouteImport
      parentRoute: typeof AppModCommunityNameRoute
    }
    '/_app/mod/$communityName/approved-users': {
      id: '/_app/mod/$communityName/approved-users'
      path: '/approved-users'
      fullPath: '/mod/$communityName/approved-users'
      preLoaderRoute: typeof AppModCommunityNameApprovedUsersRouteImport
      parentRoute: typeof AppModCommunityNameRoute
    }
    '/_app/user/$username/_profile/': {
      id: '/_app/user/$username/_profile/'
      path: '/'
      fullPath: '/user/$username/'
      preLoaderRoute: typeof AppUserUsernameProfileIndexRouteImport
      parentRoute: typeof AppUserUsernameProfileRoute
    }
    '/_app/user/$username/_profile/upvoted/': {
      id: '/_app/user/$username/_profile/upvoted/'
      path: '/upvoted'
      fullPath: '/user/$username/upvoted'
      preLoaderRoute: typeof AppUserUsernameProfileUpvotedIndexRouteImport
      parentRoute: typeof AppUserUsernameProfileRoute
    }
    '/_app/user/$username/_profile/submitted/': {
      id: '/_app/user/$username/_profile/submitted/'
      path: '/submitted'
      fullPath: '/user/$username/submitted'
      preLoaderRoute: typeof AppUserUsernameProfileSubmittedIndexRouteImport
      parentRoute: typeof AppUserUsernameProfileRoute
    }
    '/_app/user/$username/_profile/saved/': {
      id: '/_app/user/$username/_profile/saved/'
      path: '/saved'
      fullPath: '/user/$username/saved'
      preLoaderRoute: typeof AppUserUsernameProfileSavedIndexRouteImport
      parentRoute: typeof AppUserUsernameProfileRoute
    }
    '/_app/user/$username/_profile/downvoted/': {
      id: '/_app/user/$username/_profile/downvoted/'
      path: '/downvoted'
      fullPath: '/user/$username/downvoted'
      preLoaderRoute: typeof AppUserUsernameProfileDownvotedIndexRouteImport
      parentRoute: typeof AppUserUsernameProfileRoute
    }
    '/_app/user/$username/_profile/comments/': {
      id: '/_app/user/$username/_profile/comments/'
      path: '/comments'
      fullPath: '/user/$username/comments'
      preLoaderRoute: typeof AppUserUsernameProfileCommentsIndexRouteImport
      parentRoute: typeof AppUserUsernameProfileRoute
    }
  }
}

interface AppModCommunityNameRouteChildren {
  AppModCommunityNameApprovedUsersRoute: typeof AppModCommunityNameApprovedUsersRoute
  AppModCommunityNameInvitesRoute: typeof AppModCommunityNameInvitesRoute
  AppModCommunityNameModeratorsRoute: typeof AppModCommunityNameModeratorsRoute
  AppModCommunityNameIndexRoute: typeof AppModCommunityNameIndexRoute
}

const AppModCommunityNameRouteChildren: AppModCommunityNameRouteChildren = {
  AppModCommunityNameApprovedUsersRoute: AppModCommunityNameApprovedUsersRoute,
  AppModCommunityNameInvitesRoute: AppModCommunityNameInvitesRoute,
  AppModCommunityNameModeratorsRoute: AppModCommunityNameModeratorsRoute,
  AppModCommunityNameIndexRoute: AppModCommunityNameIndexRoute,
}

const AppModCommunityNameRouteWithChildren =
  AppModCommunityNameRoute._addFileChildren(AppModCommunityNameRouteChildren)

interface AppRCommunityNameRouteChildren {
  AppRCommunityNameSubmitRoute: typeof AppRCommunityNameSubmitRoute
  AppRCommunityNameIndexRoute: typeof AppRCommunityNameIndexRoute
}

const AppRCommunityNameRouteChildren: AppRCommunityNameRouteChildren = {
  AppRCommunityNameSubmitRoute: AppRCommunityNameSubmitRoute,
  AppRCommunityNameIndexRoute: AppRCommunityNameIndexRoute,
}

const AppRCommunityNameRouteWithChildren =
  AppRCommunityNameRoute._addFileChildren(AppRCommunityNameRouteChildren)

interface AppUserUsernameProfileRouteChildren {
  AppUserUsernameProfileIndexRoute: typeof AppUserUsernameProfileIndexRoute
  AppUserUsernameProfileCommentsIndexRoute: typeof AppUserUsernameProfileCommentsIndexRoute
  AppUserUsernameProfileDownvotedIndexRoute: typeof AppUserUsernameProfileDownvotedIndexRoute
  AppUserUsernameProfileSavedIndexRoute: typeof AppUserUsernameProfileSavedIndexRoute
  AppUserUsernameProfileSubmittedIndexRoute: typeof AppUserUsernameProfileSubmittedIndexRoute
  AppUserUsernameProfileUpvotedIndexRoute: typeof AppUserUsernameProfileUpvotedIndexRoute
}

const AppUserUsernameProfileRouteChildren: AppUserUsernameProfileRouteChildren =
  {
    AppUserUsernameProfileIndexRoute: AppUserUsernameProfileIndexRoute,
    AppUserUsernameProfileCommentsIndexRoute:
      AppUserUsernameProfileCommentsIndexRoute,
    AppUserUsernameProfileDownvotedIndexRoute:
      AppUserUsernameProfileDownvotedIndexRoute,
    AppUserUsernameProfileSavedIndexRoute:
      AppUserUsernameProfileSavedIndexRoute,
    AppUserUsernameProfileSubmittedIndexRoute:
      AppUserUsernameProfileSubmittedIndexRoute,
    AppUserUsernameProfileUpvotedIndexRoute:
      AppUserUsernameProfileUpvotedIndexRoute,
  }

const AppUserUsernameProfileRouteWithChildren =
  AppUserUsernameProfileRoute._addFileChildren(
    AppUserUsernameProfileRouteChildren,
  )

interface AppUserUsernameRouteChildren {
  AppUserUsernameProfileRoute: typeof AppUserUsernameProfileRouteWithChildren
}

const AppUserUsernameRouteChildren: AppUserUsernameRouteChildren = {
  AppUserUsernameProfileRoute: AppUserUsernameProfileRouteWithChildren,
}

const AppUserUsernameRouteWithChildren = AppUserUsernameRoute._addFileChildren(
  AppUserUsernameRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppModCommunityNameRoute: typeof AppModCommunityNameRouteWithChildren
  AppRCommunityNameRoute: typeof AppRCommunityNameRouteWithChildren
  AppUserUsernameRoute: typeof AppUserUsernameRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppModCommunityNameRoute: AppModCommunityNameRouteWithChildren,
  AppRCommunityNameRoute: AppRCommunityNameRouteWithChildren,
  AppUserUsernameRoute: AppUserUsernameRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignupRoute: SignupRoute,
  LoginIndexRoute: LoginIndexRoute,
  LoginSuccessIndexRoute: LoginSuccessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
