spring:
  application:
    name: threadly-services
  output:
    ansi:
      enabled: always
  modulith:
    events:
      externalization:
        amqp:
          enabled: true
          exchange: modulith.events
  rabbitmq:
    listener:
      simple:
        missing-queues-fatal: false
    template:
      mandatory: true
    dynamic: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 633490798203-cu1n5gt964mnqa9pm6lpmkog102bjnqo.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com
springdoc:
  show-actuator=true:

logging:
  level:
    org.springframework.modulith.events: TRACE
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

threadly:
  media-server:
      endpoint: http://localhost:9000
      access-key: minioadmin
      secret-key: minioadmin
  base-url: http://localhost:8080
  security:
    jwt:
      secret: UZjBmGoDLCb0PnAcmnSjZdkcZnNoN35S
      access-ms: 86400000
      refresh-ms: 1209600000
  spicedb:
      host: localhost:50051
      token: devkey