spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  application:
    name: threadly-services

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  output:
    ansi:
      enabled: always

  modulith:
    events:
      externalization:
        amqp:
          enabled: true
          exchange: modulith.events

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: /
    listener:
      simple:
        missing-queues-fatal: false
    template:
      mandatory: true
    dynamic: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com

springdoc:
  show-actuator: true

logging:
  level:
    org.springframework.modulith.events: TRACE
    org.springframework.security: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

threadly:
  base-url: http://localhost:8080

  media-server:
    endpoint: ${MEDIA_ENDPOINT:http://localhost:9000}
    access-key: ${MEDIA_ACCESS_KEY}
    secret-key: ${MEDIA_SECRET_KEY}

  security:
    jwt:
      secret: ${JWT_SECRET}
      access-ms: 86400000
      refresh-ms: 1209600000

  spicedb:
    host: localhost:50051
    token: devkey
